import type { Metadata } from 'next';
import { ReactNode } from 'react';
import '../styles/index.sass';
import StoreProvider from './StoreProvider';
import Header from '@/Components/Header/Header';
import Footer from '@/Components/Footer/Footer';
import styles from './layout.module.sass';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

type TProps = {
	children: ReactNode;
};

const RootLayout = ({ children }: TProps) => {
	return (
		<html lang='en'>
			<StoreProvider>
				<body className={styles.body}>
					<Header />
					<main className={styles.main}>{children}</main>
					<Footer />
				</body>
			</StoreProvider>
		</html>
	);
};

export default RootLayout;
